CREATE USER 'admin'@'localhost' IDENTIFIED WITH mysql_native_password BY 'admin123456';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';
FLUSH PRIVILEGES;

SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `acbf23d2_m2`
--
CREATE DATABASE IF NOT EXISTS `acbf23d2_m2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


-- --------------------------------------------------------

SET FOREIGN_KEY_CHECKS=1;
COMMIT;